<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.12" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>
</Project>