<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ComVisible>false</ComVisible>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en-GB</NeutralLanguage>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
  </PropertyGroup>

  <PropertyGroup Label="Publishing properties">
    <Company>Jim Dale</Company>
    <Copyright>© 2026 $(Company). All rights reserved.</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
  </PropertyGroup>

</Project>
